services:
  apisix:
    image: 'apache/apisix:3.2.0-debian'
    container_name: apisix
    restart: always
    volumes:
      - ./configs/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - '9180:9180/tcp'
      - '9080:9080/tcp'
      - '9091:9091/tcp'
      - '9443:9443/tcp'
    networks:
      - apisix
  dashboard:
    image: 'apache/apisix-dashboard:3.0.1-alpine'
    container_name: dashboard
    restart: always
    volumes:
      - ./configs/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml:ro
    depends_on:
      - etcd
    ports:
      - '9000:9000/tcp'
    networks:
      - apisix
  etcd:
    image: bitnami/etcd:3.4.15
    container_name: etcd
    platform: linux/amd64
    restart: always
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: 'true'
      ALLOW_NONE_AUTHENTICATION: 'yes'
      ETCD_ADVERTISE_CLIENT_URLS: 'http://etcd:2379'
      ETCD_LISTEN_CLIENT_URLS: 'http://0.0.0.0:2379'
    ports:
      - '2379:2379/tcp'
    networks:
      - apisix

volumes:
  etcd_data:
    driver: local

networks:
  apisix:
    driver: bridge
