services:
  myMariaDb:
    image: mariadb:latest
    container_name: myubuntu_mymariadb
    restart: unless-stopped
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./config/mariadb.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    networks:
      - mariadb_network
volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
networks:
  mariadb_network:
    name: mariadb_network
    driver: bridge