cluster.name: "my-cluster"
network.host: 0.0.0.0
index.store.type: hybridfs
discovery.type: single-node

xpack.security.transport.ssl.enabled: false
xpack.security.http.ssl.enabled: false
xpack.security.enabled: false
xpack.security.enrollment.enabled: false