---
services:
  opentsdb:
    hostname: otsdb-host
    platform: linux/amd64
    image: petergrace/opentsdb-docker:latest
    environment:
      - WAITSECS=30
      - DOCKER_DEFAULT_PLATFORM=linux/amd64    
    ports:
      - 4242:4242
      - 60030:60030
    volumes:  
      - "./data:/data/hbase"
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin